USE [master]
GO

/****** Object:  Database [USER_Information]    Script Date: 2016/8/1 ¤U¤È 01:47:01 ******/
CREATE DATABASE [USER_Information]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'USER_Information', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\USER_Information.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'USER_Information_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\USER_Information_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [USER_Information] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [USER_Information].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [USER_Information] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [USER_Information] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [USER_Information] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [USER_Information] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [USER_Information] SET ARITHABORT OFF 
GO

ALTER DATABASE [USER_Information] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [USER_Information] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [USER_Information] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [USER_Information] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [USER_Information] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [USER_Information] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [USER_Information] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [USER_Information] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [USER_Information] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [USER_Information] SET  DISABLE_BROKER 
GO

ALTER DATABASE [USER_Information] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [USER_Information] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [USER_Information] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [USER_Information] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [USER_Information] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [USER_Information] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [USER_Information] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [USER_Information] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [USER_Information] SET  MULTI_USER 
GO

ALTER DATABASE [USER_Information] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [USER_Information] SET DB_CHAINING OFF 
GO

ALTER DATABASE [USER_Information] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [USER_Information] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [USER_Information] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [USER_Information] SET  READ_WRITE 
GO


